option_critic_nn: 
  n_states: 1200 # TODO: Should be precomputed
  n_options: 2
  n_actions: 4

  n_steps: 4000
  n_episodes: 1000

  n_filters: [32, 64, 64]
  conv_sizes: [8, 4, 3]
  strides: [4, 2, 1]
  n_neurons: 512

  optimizer_name: "RMSProp"

  epsilon: 1 # epsilon start value
  epsilon_decay: 2e6
  epsilon_min: 0.01 
  gamma: 0.99
  beta_reg: 0.01
  entropy_reg: 0.01
  lr: 0.00025
  temperature: 1e-2

  save_frequency: 100
  verbose: false
  quiet: false

  max_history: 10000