q_learning:
  learning_rate: 0.1
  discount: 0.99
  epsilon: 1  # Exploration rate
  epsilon_decay: 0.995  # Epsilon decay per episode
  epsilon_min: 0.01  # Minimum epsilon



  qlearning_episodes: 100  # Number of Q-learning episodes