defaults:
  - base

env_name: four_rooms

# State to index mapping
state_mapping_dir: "environment/state_mapping"

env_specific_settings:
  settings: None

# Reward Function Configuration
rewards:
  goal: 1